[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "web-upload"
version = "0.1.0"
description = "Helper functions for handling web file uploads"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools]
py-modules = ["web_upload"]
